---
Name: Funke Alliyu
title: "AquaStatProject"
output: html_notebook
---


Exploring Employee Salaries


```{r}
library(data.table)
library(rvest)
library(lubridate)
library(dbplyr)
library(DataComputing)
library(magrittr)
rm(list = ls())

```




```{r}


getwd()                          #Get working directory
setwd("~/Downloads")             #Set working directory 

rawUnitdy <-read.csv("Employee_Salaries_-_2017.csv")    #Read file in table format and create a data frame from it

gc(reset=TRUE)                 #Change from data frame to data table
tracemem(rawUnitdy)
EmployeeSalaries <- as.data.table(rawUnitdy)
gc()


```



```{r}

EmployeeSalaries   #Take a look

```


```{r}
#Clean EmployeeSalaries


EmployeeSalaries <-
  EmployeeSalaries %>%
  rename(name = Full.Name, gender = Gender, annualSalary = Current.Annual.Salary, grossPay = X2017.Gross.Pay.Received, overtimePay = X2017.Overtime.Pay, dept = Department, position = Employee.Position.Title, dateHired = Date.First.Hired, deptName = Department.Name, employeeStatus = Assignment.Category) %>%
  select(-Position.Under.Filled, -Division)


str(EmployeeSalaries)


```

## Plotting Year vs. Average Salary

```{r}

EmployeeStats <-
  EmployeeSalaries %>%
  mutate(dateHired = mdy(dateHired)) %>%   #Correct variable type
  mutate(dateHired = year(dateHired)) %>%     #Change variable type to year
  mutate(year = dateHired) %>%     #rename variable
  group_by(year) %>%                   
  summarise(avgSlry = mean(annualSalary))   #average the salary per year
  


EmployeeStats %>%                           #plot regression line
  ggplot(aes(x = year, y = avgSlry)) +
  geom_point(color = "red") +
  stat_smooth(method = lm)




```




In this scatterplot one is able to see a negative correlation after the year 1985. It might be useful to focus on years after 1980.





```{r}

EmployeeStats <-
  EmployeeSalaries %>%
  mutate(dateHired = mdy(dateHired)) %>%   #Correct variable type
  mutate(dateHired = year(dateHired)) %>%     #Change variable type to year
  mutate(year = dateHired) %>%     #rename variable
  group_by(year) %>%                   
  summarise(avgSlry = mean(annualSalary)) %>%   #average the salary per year
  filter(year > 1980)            
  


EmployeeStats %>%
  ggplot(aes(x = year, y = avgSlry)) +
  geom_point(color = "red") +
  stat_smooth(method = lm)



```

After I narrowed down the year, the correlation became much stronger. In order to see how much of the avverage salary explains the yea



























